name: Deploy Subscribe

on:
  # 手动触发
  workflow_dispatch:
#  push:
#    branches: [ main ]
#  pull_request:
#    branches: [ main ]

jobs:
  build:
    # 使用ubuntu系统镜像运行自动化脚本
    runs-on: ubuntu-latest

    steps:

      # 切换分支
      - name: Checkout
        uses: actions/checkout@v2

      #      # 下载 git submodule
      #      - uses: srt32/git-actions@v0.0.3
      #        with:
      #          args: git submodule update --init --recursive

      # 使用 node:16
      - name: use Node.js 16
        id: node
        uses: actions/setup-node@v2
        with:
          node-version: '16.x'

      # 缓存 node modules
      - name: Cache node modules
        uses: actions/cache@v2
        id: cache
        env:
          cache-name: cache-node-modules
        with:
          # npm cache files are stored in `~/.npm` on Linux/macOS
          path: node_modules
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-

      # npm install
      - name: Install Dependencies
        if: steps.node.outputs.cache-hit != 'true'
        run: npm install

      # build
      - name: Build
        run: npm run build

      # tar
      - name: Tar dist
        run: tar zcf build.tar.gz dist server

      # Deploy to server
      - name: Deploy to server
        id: deploy
        uses: Pendect/action-rsyncer@v1.1.0
        env:
          DEPLOY_KEY: ${{secrets.ACCESS_TOKEN}}
        with:
          flags: '-avzr --delete'
          options: ''
          ssh_options: ''
          src: 'build.tar.gz'
          dest: '${{ secrets.REMOTE_USER }}@${{ secrets.REMOTE_HOST }}:/wwwroot/subscribe'

      # 远程Command
      - name: Command
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.REMOTE_HOST }}
          username: ${{ secrets.REMOTE_USER }}
          key: ${{ secrets.ACCESS_TOKEN }}
          script: |
            cd /wwwroot/subscribe
            tar zxf build.tar.gz
            rm build.tar.gz
            if [ ! -d "/wwwroot/subscribe/ACL4SSR" ]; then
              echo "ACL4SSR项目不存在则重新拉取"
              git clone -b master https://github.com/ACL4SSR/ACL4SSR.git
            elif [ ! -d "/wwwroot/subscribe/ACL4SSR/.git" ]; then
              echo "ACL4SSR目录存在但无git配置"
              rm -rf /wwwroot/subscribe/ACL4SSR
              git clone -b master git@github.com:ACL4SSR/ACL4SSR.git
            else
              echo "更新远程ACL4SSR项目"
              cd /wwwroot/subscribe/ACL4SSR
              git pull
            fi
            echo "更新服务端"
            cd /wwwroot/subscribe/server
            docker-compose pull && docker-compose up -d
            echo "Complete!!!"
