name: Deploy Subscribe

on:
  # 手动触发
  workflow_dispatch:
#  push:
#    branches: [ main ]
#  pull_request:
#    branches: [ main ]

jobs:
  build:
    # 使用ubuntu系统镜像运行自动化脚本
    runs-on: ubuntu-latest

    steps:

      # 切换分支
      - name: Checkout
        uses: actions/checkout@v2

      #      # 下载 git submodule
      #      - uses: srt32/git-actions@v0.0.3
      #        with:
      #          args: git submodule update --init --recursive

      # 使用 node:18
      - name: use Node.js 18
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      #安装 pnpm
      - uses: pnpm/action-setup@v2
        name: Install pnpm
        with:
          version: 8
          run_install: false

      - name: Get pnpm store directory
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_ENV

      # 缓存 node modules
      - uses: actions/cache@v3
        name: Setup pnpm cache
        with:
          path: ${{ env.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      # npm install
      - name: Install Dependencies
        run: |
          pnpm -v
          pnpm install

      # build
      - name: Build
        run: pnpm run build

      # tar
      - name: Tar dist
        run: tar zcf build.tar.gz dist server

      # Deploy to server
      - name: Deploy to server
        id: deploy
        uses: Pendect/action-rsyncer@v1.1.0
        env:
          DEPLOY_KEY: ${{secrets.ACCESS_TOKEN}}
        with:
          flags: '-avzr --delete'
          options: ''
          ssh_options: ''
          src: 'build.tar.gz'
          dest: '${{ secrets.REMOTE_USER }}@${{ secrets.REMOTE_HOST }}:/wwwroot/subscribe'

      # 远程Command
      - name: Command
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.REMOTE_HOST }}
          username: ${{ secrets.REMOTE_USER }}
          key: ${{ secrets.ACCESS_TOKEN }}
          script: |
            cd /wwwroot/subscribe
            tar zxf build.tar.gz
            rm build.tar.gz
            if [ ! -d "/wwwroot/subscribe/ACL4SSR" ]; then
              echo "ACL4SSR项目不存在则重新拉取"
              git clone -b master https://github.com/ACL4SSR/ACL4SSR.git
            elif [ ! -d "/wwwroot/subscribe/ACL4SSR/.git" ]; then
              echo "ACL4SSR目录存在但无git配置"
              rm -rf /wwwroot/subscribe/ACL4SSR
              git clone -b master git@github.com:ACL4SSR/ACL4SSR.git
            else
              echo "更新远程ACL4SSR项目"
              cd /wwwroot/subscribe/ACL4SSR
              git pull
            fi
            echo "更新服务端"
            cd /wwwroot/subscribe/server
            docker-compose pull && docker-compose up -d
            echo "Complete!!!"
