name: Deploy Subscribe

on:
  # 手动触发
  workflow_dispatch:
#  push:
#    branches: [ main ]
#  pull_request:
#    branches: [ main ]

jobs:
  build:
    # 使用ubuntu系统镜像运行自动化脚本
    runs-on: ubuntu-latest

    steps:

      # 切换分支
      - name: Checkout
        uses: actions/checkout@v4

      #      # 下载 git submodule
      #      - uses: srt32/git-actions@v0.0.3
      #        with:
      #          args: git submodule update --init --recursive

      # 使用 node:lts/iron
      - name: use Node.js lts/iron
        uses: actions/setup-node@v4
        with:
          node-version: 'lts/iron'
          cache: 'npm'

      # 缓存 node modules
      - name: Cache node modules
        uses: actions/cache@4
        id: cache
        env:
          cache-name: cache-node-modules
        with:
          # npm cache files are stored in `~/.npm` on Linux/macOS
          path: node_modules
          #path: ${{ steps.npm-cache-dir.outputs.dir }}
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      # npm install
      - name: Install Dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: npm install

      # build
      - name: Build
        run: npm run build

      # Write api_access_token
      - name: Write api_access_token
        run: |
          sed -i '6,6s/password/${{secrets.API_TOKEN}}/' ./server/replacements/pref.ini
        shell: bash

      # tar
      - name: Tar dist
        run: tar zcf build.tar.gz dist server

      # Deploy to server
      - name: Deploy to server
        id: deploy
        uses: Pendect/action-rsyncer@v2
        env:
          DEPLOY_KEY: ${{secrets.ACCESS_TOKEN}}
        with:
          flags: '-avzr --delete'
          options: ''
          ssh_options: ''
          src: 'build.tar.gz'
          dest: '${{ secrets.REMOTE_USER }}@${{ secrets.REMOTE_HOST }}:/wwwroot/subscribe'

      # 远程Command
      - name: Command
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.REMOTE_HOST }}
          username: ${{ secrets.REMOTE_USER }}
          key: ${{ secrets.ACCESS_TOKEN }}
          script: |
            cd /wwwroot/subscribe
            rm -rf dist
            tar zxf build.tar.gz
            rm build.tar.gz
            echo "更新服务端"
            cd /wwwroot/subscribe/server
            docker-compose pull && docker-compose up -d
            echo "Complete!!!"
